version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0"

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: 'echo "python3 simulatorTest.py"'
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: WebTests

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
